# Generated by Django 4.2.19 on 2025-02-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ladate',
            field=models.DateField(),
        ),
    ]
